### ISSUE TITLE
Could I use this expander for opening chart windows?

### ISSUE THREAD

**Issue by redame** [rosasurfer/mt4-expander#2]
could i use i the libary to develop my dll to control mt4 ?

**Comment by redame** [comment]
could i open new chart out of mt4 with dll or other exe?

**Comment by redame** [comment]
some question about symbols.sel in mt4
how could I update marketwatch info with update and write market info to sel file in realtime?

**Comment by rosasurfer** [comment]
First, thanks for your interest. :-) 

No, this library *is* the DLL working with/controling MT4. It's the C/C++ part of a framework. The MQL part using the DLL is a separate private Github project. 
Main purposes: 
- features not provided or not possible with MQL: e.g. communication between MQL modules: the indicator called by iCustom() can send back error codes to the calling module; the calling module can react; same for EA <-> MQL library communication.
- pointer functionality for MQL4: you can modify memory (arrays) directly 
- struct handling in MQL4; you don't need most of the non-sense features on MT5/MQL5. Everything is doable in MQL4. Of course MetaQuotes doesn't want you to know that.
- timer related functionality (self-updating offline charts). Correct indicator calculations in offline charts. Almost nobody is ware of that IndicatorCounted() does not work there. So all indicator calculations are wrong.
- creation and charting of synthetic instruments: you can attach your own pricefeed to such a synthetic instrument and it updates in realtime (something MetaQuotes just started working on in MT5; I already have it since years).
- charting of account balances and real equity charts or of equity charts resulting from backtests. for an example see the following post (the chart is generated by this framework):
https://strategyquant.com/forum/topic/can-quantanalyzer-show-helpfull-results-think-again/
- and of course working around the almost countless bugs and limitations everywhere in MQL. Ever wondered why immediately after a test in the next one the order functions still return ticket data from the previous test? The EA is not completely unloaded from memory and still contains state from the previous test.

Unfortunately Github doesn't have the feature allowing read-only access to private repositories (even for paying members). Please send a public key of yours to pewa-github@rosasurfer.com and I'll give you read-only access.

**Comment by rosasurfer** [comment]
Modifying symbols.sel is not giving you anything useful. If you know the FIX protocol, the sel file just tracks your subscribed symols and the data of the last tick. MetaQuotes just calles it "selected" instead of subscribed.

**Comment by rosasurfer** [comment]
As for the private project: The plan is to make it public too. It just needs to be cleaned up (sensitive data) and atm i don't have the time for it.

**Comment by redame** [comment]
many thanlk for your reply, and
 Now I can update chart in realtime with write the hst file via other program via MdiClient update for metaquote windows.
My purpose is to connect china stock market to mt4 and update the chart( have done ) and see the updating makret info in marketwatch,(still finding way)
Or I can creat a market info window in my program then click and open chart in mt4

**Comment by rosasurfer** [comment]
I don't have an updating marketwatch window. I have a chartinfos indicator which can show big price and spread if i want. Inter-process communication works via quickchannel.

**Comment by redame** [comment]
I have sent my publickey to you

**Comment by rosasurfer** [comment]
At the moment I'm focusing on test analysis integration into the framework. The DLL collects data and calculates test statistics which an EA might use for self-recalibration. UI for this is in the works in the mt4-tools project which is online at http:://xtrade.rosaurfer.com/

**Comment by rosasurfer** [comment]
Example of synthetic online charts: 
On the left a connected terminal which calculates prices for an non connected terminal on the right. The green light at top right signals that the chart indeed is connected, for the terminal it's a regular built-in symbol as can be seen in the symbols window. 
[synthetic chart](http://xtrade.rosasurfer.com/.intern/synthetics.png)

**Comment by redame** [comment]
I have already arrived your website before via google search to find the expander usage. 
at the moment Out team are developing a mt4 data feed plugin to view china stock market,, we have finished symbols.raw and symgroups.raw modified with china symbol and chart update with hst rewrite. both of these we don't need any mql4 and mq4 in mt4.
the only thing is updating the marketwatch still on the way, we update the chart via AfxFrameOrView and MdiClient with winddows api
updateing marketwatch windows in our plugin windows is easy to do, but i can't open mt4 chart from our plugin windows by click the symbol name.
Do have any idea for this ,
or can i make some dll  with the plugin to call mq4 function to open new chart?

**Comment by rosasurfer** [comment]
Ah, I understand. Could something with your ```symbols.raw``` be wrong? I have no problems with opening synthetic charts from MarketWatch the regular way. I just don't have prices there but I don't need them. 
http://xtrade.rosasurfer.com/.intern/marketwatch.png

**Comment by redame** [comment]
I can open chart form marketwatch that isn't update,
there are two way for me to implenment
1, I means could i open chart from outside program?
2,You have told me i cann;t update marketwatch with override the data in sel, Is there any way in menory to terminal for update marketwatch? like update chart from hst without any mq4

**Comment by redame** [comment]
My plugin isnot an another mt4 terminal,

**Comment by rosasurfer** [comment]
1) I means could i open chart from outside program?
Just send the proper message. If from outside, hook a window procedure, send a user message and translate it to whatever you want.

2) You mean which messsage to send to update the chart from hst?

**Comment by redame** [comment]
1,do you have any code to implement this way? in mql4 to open chart via chartopen(symbol period)
in my pliug there is also a symbol list,when i click one symbol in it and will trigger this symbol chart open 
2 I have finished the chart update works. MetaQuotes::MetaTrader::4.00 window and replace the handle MDIClient and send message.
by the wayI am newer in github, how could i access you rosasurfer/mt4-mql

**Comment by redame** [comment]
I searched  MetaQuotes::MetaTrader::4.00 in github so I found your code and think we are in same way

**Comment by rosasurfer** [comment]
I sent you an email with instructions to access the repo.

1,do you have any code to implement this way? in mql4 to open chart via chartopen(symbol period)

I don't have such a code because I don't need it. But it's easy to implement. Inspect the Windows message sent from the context menue in the MarketWatch window. The tricky is to find the symbol id which should be the same as in symbols raw. But beware,there are two ids. It should be ```SYMBOL.id``` at offset 120, not ```SYMBOL.arrayKey``` at 116.
I use WinSpector for this, with it you can filter messages nicely.

**Comment by rosasurfer** [comment]
there could be another way. I guess (just a guess) the built-in function ChartOpen() does exactly the same. At least this is my experience with the code in MT4. So you should be able to sniff the right message by following a ChartOpen() call with WinInspector.

**Comment by rosasurfer** [comment]
Yes, I checked (but didn't test). The docs explicitely say so:
https://docs.mql4.com/chart_operations/chartopen

You can find the message/command with WinSpector and send it manually like this:
```cpp
PostMessage(hWnd, WM_*****, lParam1, lParam2));
```

**Comment by redame** [comment]
you are kind of ppl,  It is very appreciated for you help and inspiring,
 where are you from? it is my pleasure to be friend with you in trading world and real world .
Now main work in my computer is statatics the indicator data before fastest movemnt

**Comment by redame** [comment]
![b e0q zh3z ug _rz0ha3](https://user-images.githubusercontent.com/11907023/29393463-6488d766-8336-11e7-9ee4-cf27a4788608.png)
I have tested sniffer with wininspector and get the message as image.
how about next

**Comment by redame** [comment]
`	</message>
	<message>
		<name>WM_COMMAND</name>
		<posted />
		<time>02:59:40.0213</time>
		<parameters>
			<parameter>Code: 0</parameter>
			<parameter>Control ID: 33160</parameter>
			<parameter>Control HWND: 0x00000000</parameter>
		</parameters>
	</message>
	<message>
		<name>WM_COMMAND</name>
		<posted />
		<time>02:59:40.0213</time>
		<parameters>
			<parameter>Code: 0</parameter>
			<parameter>Control ID: 33160</parameter>
			<parameter>Control HWND: 0x00000000</parameter>
		</parameters>
	</message>`

I also found command as above

**Comment by rosasurfer** [comment]
At the moment I'm quite busy, so I will come back to this later. You need to filter the messages you are not interested in, that's everything related to drawing, mouse movement, DC etc. There are hundreds of messages, it's overkill without filtering.
As for the second dump: You can see the control id (33160), that's the dynamically created one I mentioned above. Each id belongs to one symbol. You need to walk through your menu, read the text (that's the symbol) and resolve the id belonging to it. In fact, that's similar to how Windows does it by itself. If you don't have a C/Win32API programming background you will need to look for somebody who can do that for you. MQL is not C and far from enough.

If I find some time I can do it, but unfortunatelynot at this very moment. Don't be discouraged, give it a try.

**Comment by redame** [comment]
now，As you mentioned ,I cann't open the updating chart via marketwatch as online, So I have to find another method to open offline chart out of mt4 and I have know to open the offline chart select window form WM_COMMAND, 33053, and how could i find the specific file which I wanna open from my plugin only click

**Comment by rosasurfer** [comment]
Digged into the messages on ChartOpen() and found the ids. 

First the screenshot of WinSpector with filtered messages in the moment a chart is opened from the main file menu:
![Windows messages on ChartOpen](https://user-images.githubusercontent.com/12749283/29639211-a7b9ac78-8862-11e7-9f28-9afc7812e2cb.png)

As you can see after opening the "File -> New Chart" submenu (WM_COMMAND) the actual chart opening is triggered by an application registered message. It passes a command (wParam=0x0033) and an id (lParam) pointing to the symbol in the MarketWatch window:
```
lParam=0x8ca0 for the first symbol
lParam=0x8ca1 for the second symbol
lParam=0x8ca2 for the third symbol and so on.
```
The main menu "File -> New Chart" is populated with symbols in a very similar way; the menu order always reflects the symbol order in the MarketWatch window.

If you want to open a chart window you first have to inspect the MarketWatch control and read the selected symbols (you can only open charts for symbols available in MarketWatch). You read the position of the desired symbol starting with 0 (zero) and translate it to a chart id by adding 36000 (hex 0x8ca0 = decimal 36000). The resulting value (position + 36000) you pass as the second parameter (lParam) to the registered message. 
![Translated symbol ids in MarketWatch](https://user-images.githubusercontent.com/12749283/29639822-cb2b8a76-8864-11e7-8cc7-da8fd0b1c758.png)

In MQL it could look like the following test script:
```mql4
/**
 * Example script opening a chart window.
 */
#property show_inputs

extern int Symbol.Id = 36000;     // translated symbol id starting at 36000 for the top-most symbol

#import "Expander.dll"
   int  GetApplicationWindow();
   int  MT4InternalMsg();
#import "user32.dll"
   bool PostMessageA(int hWnd, int msg, int wParam, int lParam);
#import

#define MT4_OPEN_CHART           51       // hex 0x0033 = decimal 51
#define ERR_USER_ERROR_FIRST  65536

/**
 * Main function
 *
 * @return int - error status
 */
int start() {
   int hWnd = GetApplicationWindow();
   if (!hWnd) return(ERR_USER_ERROR_FIRST);

   PostMessageA(hWnd, MT4InternalMsg(), MT4_OPEN_CHART, Chart.Id);

   return(0);
}
```
You can inspect the MarketWatch control with the standard Win32 API as documented in MSDN.

**Comment by redame** [comment]
many thanks for your help and code, Now If I wanna open updating chart in mt4, I have to open offline chart as your mention, So I found the SendMessageA(hwnd, WM_COMMAND, 33053, 0) to trigger "open offline chart" window, And I think the command to open offline chart in this window,

Could you help me to find the command and position to open chart from this window?
  <message>
		<name>WM_COMMAND</name>
		<sent />
		<time>02:30:41.0727</time>
		<parameters>
			<parameter>Code: BN_CLICKED</parameter>
			<parameter>Control ID: 1</parameter>
			<parameter>Control HWND: 0x00630802</parameter>
		</parameters>
	</message>
I found this command when I open offline chart via ketboard.

**Comment by redame** [comment]
BTW I found an artical https://www.mql5.com/en/articles/2297#chapter2_1
That mean I can open offline chart via `ChartOffID = ChartOpen ( Symbol (), ExtOffPeriod);`
This code opens an offline graph with the period " ExtOffPeriod " - the truth before this is to create a history file.

**Comment by rosasurfer** [comment]
Yes, this should work. I thought about something similar. However, in general the article's approach is way to complicated, the source code is bloated and the API not abstract. In fact there is no API.

A better approach would be ```mql4/libraries/history.mq4```, the header is in ```mql4/include/history.mqh```. It's not translated (German) but you should get the improtant parts.
```mql4
/**
 * Funktionen zur Verwaltung von Historydateien.
 *
 *  • Alte MetaTrader-Versionen (Format 400) löschen beim Beenden neue Historydateien, wenn sie auf sie zugegriffen haben.
 *  • Neue MetaTrader-Versionen (Format 401) konvertieren beim Beenden alte Historydateien ins neue Format, wenn sie auf sie zugegriffen haben.
 */
#import "history.ex4"

   // Symbol-Management
   int  CreateSymbol(string name, string description, string group, int digits, string baseCurrency, string marginCurrency, string serverName="");

   // HistorySet-Management
   int  HistorySet.Create (string symbol, string description, int digits, int format, string server="");
   int  HistorySet.Get    (string symbol, string server="");
   bool HistorySet.Close  (int hSet);
   bool HistorySet.AddTick(int hSet, datetime time, double value, int flags=NULL);

   // HistoryFile-Management
   int  HistoryFile.Open     (string symbol, int timeframe, string description, int digits, int format, int mode, string server="");
   bool HistoryFile.Close    (int hFile);
   int  HistoryFile.FindBar  (int hFile, datetime time, bool lpBarExists[]);
   bool HistoryFile.ReadBar  (int hFile, int offset, double bar[]);
   bool HistoryFile.WriteBar (int hFile, int offset, double bar[], int flags=NULL);
   bool HistoryFile.UpdateBar(int hFile, int offset, double value);
   bool HistoryFile.InsertBar(int hFile, int offset, double bar[], int flags=NULL);
   bool HistoryFile.MoveBars (int hFile, int fromOffset, int destOffset);
   bool HistoryFile.AddTick  (int hFile, datetime time, double value, int flags=NULL);
#import
```
With something like this you don't work with single history files but with complete history sets. If you add a tick its added to all timeframes, not only one.

**Comment by flameOnYou** [comment]
hello,i use python to achieve oppen the chart where in markertwatch ,how can i open a offline charts which made by myself,this is my code
```python
import win32api
import win32gui


symbolid = 36000

classname = "MetaQuotes::MetaTrader::4.00"
titlename = ""
mt4 = win32gui.FindWindow(classname, None)
hwnd = mt4
print "hwnd:",hwnd
win32api.PostMessage(hwnd,expander_dll.MT4InternalMsg(),51,symbolid)

**Comment by redame** [comment]
Dear friend,
Now something are clear, They are 1)we can open online charts with winapi of you code via my plugin, And the chart can't be updated as online mode. but it can change the timeframe.
2)As you mention we can simulate the tick in offline chart which cann't change timeframe
3) I can open an online chart after offline chart, the online chart will be update like offline, even I close the offline chart.（I don;t know how about when I change timeframe of this online chart）

On you last reply, `mql4/include/history.mqh` Do you means If I write complete histry sets, I can switch the timeframe with updating onlime charts that depond on re-read hst? Plz tell me more detail about it

I got some thought from https://www.mql5.com/en/articles/2297#chapter1 this aticle
this indicator can open offline chart like online chart(must be applied in M1 chart）, the reason is period in hst header, When I `change  M2=2      // period M2`   to `  M2=5,          // period M2` It genarate a M5 online chart instead of M2 offline chart? 
I mean could I change the HST head to implement both update and timeframe switch?

best regards

**Comment by rosasurfer** [comment]
- You can always switch timeframes if the chart was opened as an online chart (from MarketWatch or from File->New Chart).

- Each timeframe will show the price history if it is available (e.g. if a history file with data exists) no matter how you opened a chart. It also doesn't matter where or who created the history file. If no history file is available switching still works but the chart window will show the message "Waiting for update".

- For the following to work **disconnect your terminal**. If you first open nine offline charts for the 9 timeframes, these nine charts will react to WM_REFRESH and re-read the history file. If after these nine charts you open one online chart of the same symbol the online chart will react to WM_REFRESH and re-read the history files the same as an offline chart **if on a multi-core machine**. You will have a chart with switchable timeframes that looks like an online chart but acts like an offline chart. This behaviour will continue if you close all of the nine offline charts you opened in the first place.

- Opening nine offline charts plus one online chart can be automated by using a chart template with nine offline charts and one online chart (in this order). Closing the nine offline charts after such a template is loaded can be automated by custom code (MQL or DLL) which iterates over all chart windows and closes only the offline charts.

**Comment by rosasurfer** [comment]
Additional note: In the above description when I say "offline charts" I mean offline charts on built-in symbols, not offline charts on self-written history files on custom symbols (like the MQL.com articles do which you mentioned). If your terminal is disconnected you can for example overwrite all nine history files of EURUSD with your Chinese index data and create an updating chart the way I described above. Or you can just create your own brand-new symbol and add it to the built-in symbols by creating a new symbol entry in ```symbols.raw```. This is what I'm doing in the charts I showed above. Timeframe-switchable and self-updating synthetic charts will only work with built-in symbols. 

In fact your terminal "thinks" your new symbol is a regular broker symbol. It doesn't see the difference.
