### ISSUE TITLE
Creating MT4 multi charts

### ISSUE THREAD

**Issue by OlaSeye** [rosasurfer/mt4-expander#3]
I want to design a script to position MT4 charts in a cascade manner. How do I implement this.
I have a script attached below am modifying

[WInHandle MT4.txt](https://github.com/rosasurfer/mt4-expander/files/2740663/WInHandle.MT4.txt)

**Comment by OlaSeye** [comment]
![image](https://user-images.githubusercontent.com/46485565/50896732-43b9f680-140a-11e9-8ab2-ab83b16a6520.png)

I want the scripts to arrange the charts already opened in MT4

**Comment by rosasurfer** [comment]
Why would you need a script to achieve that? There is a multitude of cascade options in the "Window" menu.
![cascade-windows](https://user-images.githubusercontent.com/12749283/64286440-22dc7d80-cf66-11e9-8867-a795de77abe1.png)
