### ISSUE TITLE
Can you turn ShiftIndicatorBuffer into a template

### ISSUE THREAD

**Issue by Janaue** [rosasurfer/mt4-expander#6]
I want to use the ShiftIndicatorBuffer from the dll rsfMT4Expander.dll

https://github.com/rosasurfer/mt4-expander/blob/47dbb1a57439b233117f7b141c6b4b010f39e57a/src/util/helper.cpp

```
/**
 * Shifted die Werte eines IndicatorBuffers um eine Anzahl von Bars nach hinten. Die ältesten Werte verfallen.
 *
 * @param  double buffer[]   - MQL-Double-Array (IndicatorBuffer)
 * @param  int    bufferSize - Größe des Arrays
 * @param  int    bars       - Anzahl der zu shiftenden Bars
 * @param  double emptyValue - Initialisierungswert für freiwerdende Bufferelemente
 *
 * @return BOOL - Erfolgsstatus
 **/

BOOL WINAPI ShiftIndicatorBuffer(double buffer[], int bufferSize, int bars, double emptyValue) {
   if (buffer && (uint)buffer < MIN_VALID_POINTER) return(error(ERR_INVALID_PARAMETER, "invalid parameter buffer = 0x%p (not a valid pointer)", buffer));
   if (bufferSize < 0)                             return(error(ERR_INVALID_PARAMETER, "invalid parameter bufferSize = %d", bufferSize));
   if (bars < 0)                                   return(error(ERR_INVALID_PARAMETER, "invalid parameter bars = %d", bars));
   if (!bufferSize || !bars) return(TRUE);

   MoveMemory((void*)&buffer[0], &buffer[bars], (bufferSize-bars)*sizeof(buffer[0]));

   for (int i=bufferSize-bars; i < bufferSize; i++) {
      buffer[i] = emptyValue;
   }
   return(TRUE);
   #pragma EXPANDER_EXPORT
}
```

but I a big number of buffers and I have various types of buffers, like ''char'' , ''long'' and so on so I really need a template for this. So instead of only ''double'', ShiftIndicatorBuffer(double buffer[], int bufferSize, int bars, double emptyValue) would take any type of buffer and MQL will do whatever it has to do to make sens of it.

**Comment by rosasurfer** [comment]
Rewriting the functions using templates to support MQL5 data types in the development branch. Once finished the changes will show up in master.

https://github.com/rosasurfer/mt4-expander/blob/development/src/lib/array.cpp

**Comment by Janaue** [comment]
OK I was coming from 
https://www.mql5.com/en/forum/217490#comment_5918810
because the behavior for offline chart is just insane.
He says ''While it is possible to implement it in MQL for performance reasons it is strongly recommended to move the code to a DLL where memory can be moved directly without using loops:'' but since I cant get template with functions from a DLL, I am willing to try the approach with poor performance.
However I don't know how to code this in MQL
`MoveMemory((void*)&buffer[0], &buffer[count], (size-count)*sizeof(buffer[0]));

   std::fill_n(&buffer[size-count], count, emptyValue);`

Can you give the MQL equivalent to your DLL trick, ideally as a template?

**Comment by rosasurfer** [comment]
This is me on mql5.com (a long time ago, I'm not active there anymore), and using the DLL without template functions is perfectly fine. Look at the development branch (link two posts above). There are now functions for all MQL5 data types. Currently I'm testing the behavior for unsigned data types.

Compiled DLL in this directory: https://github.com/rosasurfer/mt4-mql/tree/development/mql4/libraries

Import declarations:
https://github.com/rosasurfer/mt4-mql/blob/0ecc35da8b80b9a6300e15238c1479987d282f78/mql4/include/api.mqh#L946

```
#import "rsfMT4Expander.dll"
   // ...insert what you need from api.mqh
#import
```

But as said at the moment everything is still in development branches and subject to change. After finishing of work changes will show up in the master branches.

**Comment by rosasurfer** [comment]
Changes are merged to master: [array.cpp](https://github.com/rosasurfer/mt4-expander/blob/master/src/lib/array.cpp), [api.mqh](https://github.com/rosasurfer/mt4-mql/blob/master/mql4/include/api.mqh), [DLL](https://github.com/rosasurfer/mt4-mql/blob/master/mql4/libraries/rsfMT4Expander.dll) (notice the `Download` button)

Following an example using an `int[]` array:

![ShiftIntIndicatorBuffer](https://user-images.githubusercontent.com/12749283/171994351-445147cc-a318-438d-a722-04177d3ef42b.png)
![ShiftIntIndicatorBuffer DebugView](https://user-images.githubusercontent.com/12749283/171994356-b0e1f05a-9ff4-4690-a1e6-18752c4274d1.png)

- First the array is manually initialized with some values. 
- Then `InitializeIntArray()` is called to re-initialize a range of the array with a different value (`111`). 
- Last `ShiftIntIndicatorBuffer()` is called to shift-off the first two elements of the array and fill the now empty elements at the end with another value (`222`).

**Comment by Janaue** [comment]
So now I only need to import this, using the overload feature of MQL,

#import "rsfMT4Expander.dll"
bool ShiftIndicatorBuffer(bool&buffer[],int bufferSize,int bars,bool emptyValue);
bool ShiftIndicatorBuffer(char&buffer[],int bufferSize,int bars,char emptyValue);
bool ShiftIndicatorBuffer(double&buffer[],int bufferSize,int bars,double emptyValue);
bool ShiftIndicatorBuffer(float&buffer[],int bufferSize,int bars,float emptyValue);
bool ShiftIndicatorBuffer(int&buffer[],int bufferSize,int bars,int emptyValue);
bool ShiftIndicatorBuffer(long&buffer[],int bufferSize,int bars,long emptyValue);
bool ShiftIndicatorBuffer(short&buffer[],int bufferSize,int bars,short emptyValue);   
#import 

and I can I get this generic ShiftIndicatorBuffer directly in my .mql4, do you confirm?
